#https://youtube.com/shorts/E_Q2tyN7E-Y?si=V2Yak8jkRa5lLm3v
#Cabrera,PrincessKyleDeniseT.

TERMS_AND_DEFINITIONS = {
    "MAGNETISM": "THE FORCE EXERTED BY MAGNETS WHEN THEY ATTRACT OR REPEL EACH OTHER",
    "AMPLITUDE": "THE MAXIMUM EXTENT OF A VIBRATION OR OSCILLATION, MEASURED FROM THE POSITION OF EQUILIBRIUM.",
    "ANALOG": "A TYPE OF SIGNAL THAT IS CONTINUOUS AND CAN TAKE ANY VALUE WITHIN A GIVEN RANGE.",
    "BINARY": "A SYSTEM OF NUMERICAL NOTATION THAT HAS 2 RATHER THAN 10 AS A BASE",
    "CAPACITANCE": "THE ABILITY OF A SYSTEM TO STORE AN ELECTRIC CHARGE",
    "CIRCUIT": "A COMPLETE AND CLOSED PATH AROUND WHICH A CIRCULATING ELECTRIC CURRENT CAN FLOW.",
    "CONDUCTOR": "A MATERIAL OR OBJECT THAT PERMITS AN ELECTRIC CURRENT T FLOW EASILY.",
    "CONTROL SYSTEM": "A SYSTEM THAT MANAGES, COMMANDS, DIRECTS, OR REGULATES THE BEHAVIOR OF OTHER DEVICES OR SYSTEMS.",
    "DIELECTRIC": "AN INSULATING MATERIAL THAT CAN BE POLARIZED BY AN ELECTRIC FIELD",
    "DIFFUSION": "THE SPREADING OF SOMETHING MORE WIDELY. OFTEN USED IN RELATION TO GASES OR LIQUIDS.",
    "DYNAMICS": "THE BRANCH OF MECHANICS CONCERNED WITH THE MOTION OF BODIES UNDER THE ACTION OF FORCES.",
    "EFFICIENCY": "THE RATIO OF THE USEFUL OUTPUT OF A SYSTEM TO THE INPUT, EXPRESSED AS A PERCENTAGE.",
    "ENTROPY": "A MEASURE OF DISORDER OR RANDOMNESS IN A SYSTEM",
    "FEEDBACK": "INFORMATION ABOUT REACTIONS TO A PRODUCT, A PERSON'S PERFORMANCE, USED AS A BASIS FOR IMPROVEMENT.",
    "FREQUENCY": "THE RATE AT WHICH A VIBRATION OCCURS THAT CONSTITUTES A WAVE, EITHER IN A MATERIAL OR IN AN ELECTROMAGNETIC FIELD",
    "FUSION": "THE PROCESS OR RESULT OF JOINING TWO OR MORE THINGS TOGETHER TO FORM A SINGLE ENTITY.",
    "GANTRY": "A STRUCTURE USED TO SUPPORT A CRANE OR OTHER EQUIPMENT.",
    "HYDRAULICS": "THE SCIENCE OF THE MECHANICAL PROPERTIES OF LIQUIDS",
    "IMPEDANCE": "THE TOTAL OPPOSITION THAT A CIRCUIT OFFERS TO THE FLOW OF ALTERNATING CURRENT.",
    "INDUCTANCE": "THE PROPERTY OF AN ELECTRIC CIRCUIT BY WHICH A CHANGING MAGNETIC FIELD CREATES AN ELECTROMOTIVE FORCE.",
    "INERTIA": "THE RESISTANCE OF ANY PHYSICAL OBJECT TO A CHANGE IN ITS STATE OF MOTION OR REST",
    "INSULATION": "THE PROCESS OF KEEPING HEAT, SOUND, OR ELECTRICITY FROM SPREADING.",
    "JOULE": "A UNIT OF ENERGY IN THE INTERNATIONAL SYSTEM OF UNITS.",
    "KINEMATICS": "THE BRANCH OF MECHANICS THAT DESCRIBES THE MOTION OF POINTS, BODIES, AND SYSTEMS WITHOUT CONSIDERING THE FORCES THAT CAUSE THEM.",
    "TORQUE": "A MEASURE OF THE FORCE THAT CAN CAUSE AN OBJECT TO ROTATE ABOUT AN AXIS.",
    "POWER": "THE RATE AT WHICH WORK IS DONE OR ENERGY IS TRANSFERRED",
    "RESISTANCE": "A MEASURE OF THE OPPOSITION TO CURRENT FLOW IN AN ELECTRICAL CIRCUIT.",
    "RESONANCE": "THE REINFORCEMENT OR PROLONGATION OF SOUND BY REFLECTION FROM A SURFACE OR BY THE SYNCHRONOUS VIBRATION OF A NEIGHBORING OBJECT.",
    "OHM": "THE UNIT OF ELECTRICAL RESISTANCE IN THE INTERNATIONAL SYSTEM OF UNITS",
    "PHOTONICS": "THE SCIENCE AND TECHNOLOGY OF GENERATING, CONTROLLING, AND DETECTING PHOTONS."
}


a = input("SEARCH THE DEFINITION OF:")

print(TERMS_AND_DEFINITIONS.get(a.upper(),"term not found."))